---
name: Release
on:
  push:
    tags:
      - "v*.*.*"
permissions: read-all
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clear Libs folder. It will be created from scratch
        run: |
          rm -rf Libs/

      - name: Package and release
        uses: BigWigsMods/packager@master
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOW_INTERFACE_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_KEY }}
